spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://mysql/auth
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: devkim
      password: qwe1212
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

kakao:
  client_id: b5b4e67b3c1c519d3dd172cdc4cd5cc8
  redirect_uri: http://localhost:8080/kakao/callback